// FanDNA per-sport voice (the "register"): the noun, what you wear, the team words, the league
// labels, the result tail, and the cross-match header/escape. ONE source of truth, read by both
// the app (result screen) and the share card, so a sport's voice lives in exactly one place and
// the two can never drift. Adding a sport is one row here. PL/NFL/MLB are unchanged.
const REGISTER = {
  PL:  { noun: "club",      worn: "shirt",  team: "club", teams: "clubs", league: "Premier League", leagueAbbr: "PL", leagueIn: "the Premier League",
         tail: "What you support on Saturdays is up to you.",
         xmHeader: "Already have a favourite club?", xmEscape: "I don't support a Premier League club" },
  NFL: { noun: "franchise", worn: "jersey", team: "team", teams: "teams", league: "NFL", leagueAbbr: "NFL", leagueIn: "the NFL",
         tail: "What you support on Sundays is up to you.",
         xmHeader: "Already root for a team?", xmEscape: "I don't follow an NFL team" },
  MLB: { noun: "ballclub",  worn: "cap",    team: "team", teams: "teams", league: "MLB", leagueAbbr: "MLB", leagueIn: "MLB",
         tail: "What you root for at the ballpark is up to you.",
         xmHeader: "Already have a ballclub?", xmEscape: "I don't have an MLB team" },
  NBA: { noun: "team",      worn: "jersey", team: "team", teams: "teams", league: "NBA", leagueAbbr: "NBA", leagueIn: "the NBA",
         tail: "What you cheer for on gameday is up to you.",
         xmHeader: "Already have a team?", xmEscape: "I don't follow an NBA team" },
  BL:  { noun: "club",      worn: "scarf",  team: "club", teams: "clubs", league: "Bundesliga", leagueAbbr: "BL", leagueIn: "the Bundesliga",
         tail: "Who you sing for on matchday is up to you.",
         xmHeader: "Already have a Bundesliga club?", xmEscape: "I don't support a Bundesliga club" },
  LL:  { noun: "club",      worn: "shirt",  team: "club", teams: "clubs", league: "La Liga", leagueAbbr: "LL", leagueIn: "La Liga",
         tail: "Who you live for, win or lose, is up to you.",
         xmHeader: "Already have a La Liga club?", xmEscape: "I don't support a La Liga club" },
  L1:  { noun: "club",      worn: "scarf",  team: "club", teams: "clubs", league: "Ligue 1", leagueAbbr: "L1", leagueIn: "Ligue 1",
         tail: "Who you turn up for, week after week, is up to you.",
         xmHeader: "Already have a Ligue 1 club?", xmEscape: "I don't support a Ligue 1 club" },
  SA:  { noun: "club",      worn: "scarf",  team: "club", teams: "clubs", league: "Serie A", leagueAbbr: "SA", leagueIn: "Serie A",
         tail: "Who you'd lose your voice for, Sunday after Sunday, is up to you.",
         xmHeader: "Already have a Serie A club?", xmEscape: "I don't support a Serie A club" },
  CFB: { noun: "program",   worn: "jersey", team: "program", teams: "programs", league: "College Football", leagueAbbr: "CFB", leagueIn: "college football",
         tail: "Where you spend your fall Saturdays is up to you.",
         xmHeader: "Already have a program?", xmEscape: "I don't follow college football" },
  NHL: { noun: "team",      worn: "sweater", team: "team", teams: "teams", league: "NHL", leagueAbbr: "NHL", leagueIn: "the NHL",
         tail: "Where you spend your winter nights is up to you.",
         xmHeader: "Already have a team?", xmEscape: "I don't follow an NHL team" },
  F1:  { noun: "team",      worn: "colours", team: "team", teams: "teams", league: "Formula 1", leagueAbbr: "F1", leagueIn: "Formula 1",
         tail: "Which garage you pull for on Sundays is up to you.",
         xmHeader: "Already have a team?", xmEscape: "I don't follow Formula 1" },
  AFL: { noun: "club",      worn: "guernsey", team: "club", teams: "clubs", league: "AFL", leagueAbbr: "AFL", leagueIn: "the AFL",
         tail: "Who you barrack for come September is up to you.",
         xmHeader: "Already have a club?", xmEscape: "I don't follow the AFL" },
  IPL: { noun: "franchise",  worn: "jersey", team: "franchise", teams: "franchises", league: "IPL", leagueAbbr: "IPL", leagueIn: "the IPL",
         tail: "Who you roar for through the summer is up to you.",
         xmHeader: "Already have a franchise?", xmEscape: "I don't follow the IPL" },
  TOP14: { noun: "club",     worn: "shirt", team: "club", teams: "clubs", league: "Top 14", leagueAbbr: "Top 14", leagueIn: "the Top 14",
         tail: "Who you sing for on a Saturday is up to you.",
         xmHeader: "Already have a club?", xmEscape: "I don't follow the Top 14" },
};
function regOf(s){ return REGISTER[s] || REGISTER.PL; }

export { REGISTER, regOf };
