// whyYou.js - computed 'Why you' beats (s61, display-only). Reads the taker's coreProfile
// and the club's teamDims; never touches scoring. Surfaces the taker's most pronounced
// core traits that (a) the club also leans, and (b) the club's portrait (desc) does NOT
// already foreground - so it complements 'Your match' instead of restating it.
// FOREGROUND is authored per club from its desc text (pole-agnostic). Fully editable:
// to change a club's routing, edit its 'SPORT:CODE' row below. No rebuild of logic needed.
import { decompressProfile } from './scoring';

const DIM = ['loyalty','emotion','ambition','process','community','chaos','rootedness'];
const MEAN = { loyalty:6.2, emotion:6.2, ambition:6.251, process:5.096, community:5.266, chaos:5.235, rootedness:5.729 };
const SD   = { loyalty:1.736, emotion:1.11, ambition:1.402, process:1.88, community:1.981, chaos:2.197, rootedness:1.745 };

// Trait -> pole -> line. Person-first, ~90 chars, no em dash, no fragment, trait not role.
const PHRASING = {
  loyalty:    { high:'You are all the way in or not at all, and once you commit, walking away is off the table.',
                low:'You keep a little distance on purpose. You would rather stay clear-eyed than pledge blindly.' },
  emotion:    { high:'You feel everything at full volume, and there is no quiet version of you when it matters.',
                low:'You run cool when it counts. You would rather stay level than get swept up in the swell of it.' },
  ambition:   { high:'You are pulled toward the top and you do not pretend otherwise. Second best sits badly with you.',
                low:'Winning is not the whole point for you. You would take the doing of it over the trophy at the end.' },
  process:    { high:'You do a thing properly or you leave it alone. Half-built and good-enough sit wrong with you.',
                low:'You do not need it all controlled and planned. You are content to let it stay a little loose.' },
  community:  { high:'You are pulled toward being part of something larger than yourself, a whole thing moving as one.',
                low:'You are drawn to the thing itself more than the crowd around it. Belonging matters less than doing.' },
  chaos:      { high:'A bit of drama does not scare you. You are drawn to the swing of it, the risk it could go either way.',
                low:'You want it steady, not chaotic. You would rather build something dependable than ride the swings.' },
  rootedness: { high:'You belong somewhere and you feel it. You would rather go deep where you are than start fresh.',
                low:'You are not tied to one place. You would follow the thing you love wherever it goes.' },
};

// Traits each club's desc already foregrounds (so 'why' routes around them).
const FOREGROUND = {
  "AFL:ADE": ["ambition"],
  "AFL:BRL": ["ambition","chaos"],
  "AFL:CAR": ["ambition","loyalty","rootedness","emotion"],
  "AFL:COL": ["ambition","emotion","rootedness"],
  "AFL:ESS": ["ambition","loyalty"],
  "AFL:FRE": ["ambition","community","emotion","loyalty"],
  "AFL:GCS": ["ambition","rootedness"],
  "AFL:GEE": ["ambition","community","loyalty"],
  "AFL:GWS": ["community","rootedness"],
  "AFL:HAW": ["ambition","loyalty","process"],
  "AFL:MEL": ["ambition","loyalty","rootedness"],
  "AFL:NTH": ["chaos","community","rootedness"],
  "AFL:PTA": ["ambition","emotion","rootedness"],
  "AFL:RIC": ["ambition","chaos","emotion"],
  "AFL:STK": ["ambition","emotion","loyalty"],
  "AFL:SYD": ["ambition","chaos","emotion"],
  "AFL:WBD": ["ambition","community","loyalty"],
  "AFL:WCE": ["ambition"],
  "BL:B04": ["ambition"],
  "BL:BAY": ["ambition","chaos","emotion"],
  "BL:BMG": ["ambition","loyalty"],
  "BL:BVB": ["community","emotion","loyalty"],
  "BL:ELV": ["ambition","community","emotion"],
  "BL:FCA": ["ambition","chaos"],
  "BL:FCU": ["community","emotion"],
  "BL:HSV": [],
  "BL:KOE": ["chaos","emotion","loyalty"],
  "BL:M05": ["chaos","community","emotion"],
  "BL:RBL": ["community","loyalty","process"],
  "BL:S04": ["ambition","loyalty","process"],
  "BL:SCF": ["loyalty","process"],
  "BL:SCP": ["chaos"],
  "BL:SGE": ["community","emotion"],
  "BL:SVW": ["chaos","loyalty"],
  "BL:TSG": ["community","loyalty","process"],
  "BL:VFB": ["ambition","loyalty","process"],
  "CFB:AIR": ["ambition","loyalty","process"],
  "CFB:ALA": ["ambition","rootedness"],
  "CFB:APP": ["ambition","community"],
  "CFB:ARK": ["community","emotion","loyalty"],
  "CFB:ARM": ["ambition","chaos"],
  "CFB:AUB": ["ambition","chaos","emotion"],
  "CFB:BOI": ["ambition","loyalty"],
  "CFB:BYU": ["ambition","community","loyalty"],
  "CFB:CLM": ["ambition","emotion","loyalty"],
  "CFB:COL": ["ambition","emotion","loyalty"],
  "CFB:CST": ["chaos","emotion","rootedness"],
  "CFB:ECU": ["process"],
  "CFB:FLA": ["ambition"],
  "CFB:FSU": ["ambition","chaos","process"],
  "CFB:GAT": ["ambition","emotion","rootedness"],
  "CFB:HAW": ["chaos","community","loyalty"],
  "CFB:IND": ["ambition"],
  "CFB:IOW": ["ambition","process"],
  "CFB:KSU": ["ambition","loyalty","process"],
  "CFB:LSU": ["ambition","community","emotion"],
  "CFB:MAR": ["ambition","community","emotion"],
  "CFB:MIA": ["ambition","chaos","emotion"],
  "CFB:MIC": ["ambition","chaos","community"],
  "CFB:MST": ["ambition","community","emotion"],
  "CFB:MSU": ["ambition","emotion","process"],
  "CFB:NAV": ["chaos","loyalty","process"],
  "CFB:NDM": ["ambition","emotion","loyalty"],
  "CFB:NEB": ["ambition","loyalty"],
  "CFB:OKL": ["ambition"],
  "CFB:OKS": ["emotion","loyalty","rootedness"],
  "CFB:OLE": ["ambition","chaos","emotion"],
  "CFB:ORE": ["ambition","chaos"],
  "CFB:OSU": ["ambition","emotion","loyalty"],
  "CFB:PSU": ["ambition","emotion","process"],
  "CFB:SCA": ["ambition","community","emotion"],
  "CFB:SMU": ["ambition","chaos","rootedness"],
  "CFB:STA": ["ambition","emotion","process"],
  "CFB:TAM": ["community","emotion","loyalty"],
  "CFB:TCU": ["ambition","emotion","loyalty"],
  "CFB:TEN": ["ambition","community","loyalty"],
  "CFB:TEX": ["ambition"],
  "CFB:TTU": ["chaos","emotion","loyalty"],
  "CFB:TUL": ["ambition","emotion"],
  "CFB:UCF": ["ambition","chaos","community"],
  "CFB:UGA": ["ambition","emotion","loyalty","process"],
  "CFB:USC": ["ambition","rootedness"],
  "CFB:VAN": ["ambition","process"],
  "CFB:VAT": ["ambition","emotion","loyalty"],
  "CFB:WAS": ["ambition","community","loyalty"],
  "CFB:WAZ": ["ambition","emotion","loyalty"],
  "CFB:WIS": ["ambition","emotion","process"],
  "CFB:WVU": ["ambition","community"],
  "F1:ALP": ["ambition","chaos","emotion","loyalty"],
  "F1:AST": ["ambition","community","process"],
  "F1:AUD": ["ambition","loyalty","process"],
  "F1:CAD": ["ambition","community"],
  "F1:FER": ["ambition","emotion","loyalty"],
  "F1:HAA": ["ambition","chaos","emotion"],
  "F1:MCL": ["ambition","chaos","process"],
  "F1:MER": ["ambition","emotion","process"],
  "F1:RB": ["ambition","loyalty"],
  "F1:RBR": ["ambition","community","process"],
  "F1:WIL": ["ambition","loyalty","process"],
  "IPL:CSK": ["ambition","chaos","loyalty","rootedness"],
  "IPL:DC": ["ambition","chaos","process"],
  "IPL:GT": ["ambition","chaos","loyalty"],
  "IPL:KKR": ["community","loyalty","process"],
  "IPL:LSG": ["ambition","chaos"],
  "IPL:MI": ["ambition","loyalty","process"],
  "IPL:PBKS": ["ambition","chaos","emotion"],
  "IPL:RCB": ["ambition","emotion","loyalty"],
  "IPL:RR": ["chaos","emotion","loyalty"],
  "IPL:SRH": ["ambition","emotion","loyalty"],
  "L1:AJA": ["community","loyalty","process"],
  "L1:ANG": ["ambition","chaos"],
  "L1:BRE": ["ambition","community","emotion"],
  "L1:HAC": ["ambition","chaos","rootedness"],
  "L1:LEM": ["ambition","chaos","loyalty"],
  "L1:LEN": ["community","emotion","rootedness"],
  "L1:LIL": ["ambition","community"],
  "L1:LOR": ["ambition","rootedness"],
  "L1:LYO": ["ambition","emotion"],
  "L1:MAR": ["ambition","emotion","loyalty"],
  "L1:MON": ["ambition","community","emotion"],
  "L1:NIC": ["ambition","community","process"],
  "L1:PFC": ["ambition"],
  "L1:PSG": ["ambition","emotion","loyalty"],
  "L1:REN": ["loyalty"],
  "L1:STR": ["loyalty","rootedness"],
  "L1:TOU": ["ambition","loyalty","process"],
  "L1:TRO": ["ambition","loyalty","process"],
  "LL:ALA": ["ambition","emotion","loyalty"],
  "LL:ATH": ["ambition","loyalty","process"],
  "LL:ATM": ["ambition","emotion","loyalty"],
  "LL:BAR": ["ambition","emotion","loyalty"],
  "LL:BET": ["community","emotion","loyalty"],
  "LL:CEL": ["loyalty","rootedness"],
  "LL:DEP": ["ambition","loyalty"],
  "LL:ELC": ["chaos"],
  "LL:ESP": ["chaos","emotion","loyalty"],
  "LL:GET": ["chaos","emotion"],
  "LL:LEV": ["ambition","emotion","loyalty"],
  "LL:MAL": ["loyalty"],
  "LL:OSA": ["community","rootedness"],
  "LL:RAC": ["ambition","community","rootedness"],
  "LL:RAY": ["chaos"],
  "LL:RMA": ["ambition","loyalty"],
  "LL:RSO": ["ambition","loyalty"],
  "LL:SEV": ["loyalty","process"],
  "LL:VAL": ["ambition","community","loyalty"],
  "LL:VIL": ["ambition","loyalty","process"],
  "MLB:ATH": ["loyalty","process"],
  "MLB:ATL": ["ambition","emotion"],
  "MLB:AZ": ["ambition","chaos","loyalty"],
  "MLB:BAL": ["community","process","rootedness"],
  "MLB:BOS": ["ambition"],
  "MLB:CHC": ["ambition","emotion","loyalty"],
  "MLB:CIN": ["ambition","process","rootedness"],
  "MLB:CLE": ["ambition","loyalty","process"],
  "MLB:COL": ["ambition","emotion"],
  "MLB:CWS": ["loyalty","rootedness"],
  "MLB:DET": ["ambition"],
  "MLB:HOU": ["ambition","process"],
  "MLB:KC": ["ambition"],
  "MLB:LAA": ["ambition","emotion","loyalty"],
  "MLB:LAD": ["ambition","chaos","emotion"],
  "MLB:MIA": ["ambition","chaos","emotion"],
  "MLB:MIL": ["ambition","emotion"],
  "MLB:MIN": ["ambition","emotion","process"],
  "MLB:NYM": ["ambition","emotion"],
  "MLB:NYY": ["ambition","rootedness"],
  "MLB:PHI": ["community","emotion"],
  "MLB:PIT": ["community","loyalty","rootedness"],
  "MLB:SD": ["ambition"],
  "MLB:SEA": ["ambition"],
  "MLB:SF": ["ambition","emotion"],
  "MLB:STL": ["ambition","chaos","process"],
  "MLB:TB": ["ambition","community","process"],
  "MLB:TEX": ["ambition","community","emotion"],
  "MLB:TOR": ["ambition","community","emotion"],
  "MLB:WSH": ["ambition","emotion"],
  "NBA:ATL": ["ambition","community","loyalty"],
  "NBA:BKN": ["ambition","chaos"],
  "NBA:BOS": ["ambition","emotion"],
  "NBA:CHA": ["community"],
  "NBA:CHI": ["ambition","chaos","community"],
  "NBA:CLE": ["ambition","emotion"],
  "NBA:DAL": ["ambition","emotion","loyalty"],
  "NBA:DEN": ["ambition","process"],
  "NBA:DET": ["ambition","loyalty"],
  "NBA:GSW": ["ambition","community","process"],
  "NBA:HOU": ["ambition","process"],
  "NBA:IND": ["ambition","emotion","loyalty"],
  "NBA:LAC": ["loyalty"],
  "NBA:LAL": ["ambition"],
  "NBA:MEM": ["emotion","process"],
  "NBA:MIA": ["ambition","process"],
  "NBA:MIL": ["ambition","community","process"],
  "NBA:MIN": ["ambition","emotion","loyalty"],
  "NBA:NOP": ["ambition","emotion"],
  "NBA:NYK": ["ambition","emotion","loyalty"],
  "NBA:OKC": ["ambition","community","process"],
  "NBA:ORL": ["ambition","emotion","loyalty"],
  "NBA:PHI": ["emotion","process"],
  "NBA:PHX": ["emotion"],
  "NBA:POR": ["ambition","emotion","loyalty"],
  "NBA:SAC": ["ambition","community","loyalty"],
  "NBA:SAS": ["ambition","chaos","emotion","process"],
  "NBA:TOR": ["ambition","emotion","loyalty"],
  "NBA:UTA": ["ambition","process"],
  "NBA:WAS": ["ambition","emotion","loyalty"],
  "NFL:ARI": ["ambition","community"],
  "NFL:ATL": ["emotion"],
  "NFL:BAL": [],
  "NFL:BUF": ["ambition","emotion","loyalty"],
  "NFL:CAR": ["ambition","chaos","rootedness"],
  "NFL:CHI": ["ambition","community"],
  "NFL:CIN": [],
  "NFL:CLE": ["ambition","emotion"],
  "NFL:DAL": ["ambition"],
  "NFL:DEN": ["ambition","community","rootedness"],
  "NFL:DET": ["ambition","chaos","loyalty"],
  "NFL:GB": ["ambition","community"],
  "NFL:HOU": ["ambition","emotion"],
  "NFL:IND": ["ambition"],
  "NFL:JAX": ["community","emotion","loyalty"],
  "NFL:KC": ["ambition","community"],
  "NFL:LAC": ["ambition","emotion","loyalty"],
  "NFL:LAR": ["ambition"],
  "NFL:LV": ["ambition","community"],
  "NFL:MIA": ["ambition","emotion"],
  "NFL:MIN": ["ambition","community","emotion"],
  "NFL:NE": ["ambition","emotion","rootedness"],
  "NFL:NO": ["ambition"],
  "NFL:NYG": ["ambition","loyalty"],
  "NFL:NYJ": ["ambition","chaos"],
  "NFL:PHI": ["loyalty"],
  "NFL:PIT": ["community","loyalty"],
  "NFL:SEA": ["community","emotion"],
  "NFL:SF": ["ambition"],
  "NFL:TB": ["ambition","community","loyalty"],
  "NFL:TEN": ["ambition"],
  "NFL:WAS": ["ambition","community","loyalty"],
  "NHL:ANA": ["ambition","chaos"],
  "NHL:BOS": ["ambition","rootedness"],
  "NHL:BUF": ["ambition","emotion","loyalty"],
  "NHL:CAR": ["ambition","emotion","loyalty"],
  "NHL:CBJ": ["ambition","emotion","loyalty"],
  "NHL:CGY": ["ambition","community","loyalty"],
  "NHL:CHI": ["ambition","chaos","emotion"],
  "NHL:COL": ["ambition"],
  "NHL:DAL": ["ambition"],
  "NHL:DET": ["ambition","community","process"],
  "NHL:EDM": ["ambition","chaos","emotion"],
  "NHL:FLA": ["ambition","emotion","loyalty"],
  "NHL:LAK": ["ambition","emotion"],
  "NHL:MIN": ["ambition","loyalty","rootedness"],
  "NHL:MTL": ["ambition","emotion","loyalty"],
  "NHL:NJD": ["ambition","chaos","process"],
  "NHL:NSH": ["ambition","emotion","rootedness"],
  "NHL:NYI": ["ambition","emotion"],
  "NHL:NYR": ["ambition","emotion"],
  "NHL:OTT": ["ambition","community","loyalty"],
  "NHL:PHI": ["ambition","loyalty"],
  "NHL:PIT": ["ambition","chaos"],
  "NHL:SEA": ["ambition"],
  "NHL:SJS": ["ambition","loyalty"],
  "NHL:STL": ["ambition","emotion","loyalty"],
  "NHL:TBL": ["ambition","loyalty","process"],
  "NHL:TOR": ["ambition","emotion","rootedness"],
  "NHL:UTA": [],
  "NHL:VAN": ["ambition","emotion","loyalty"],
  "NHL:VGK": ["ambition","emotion","process"],
  "NHL:WPG": ["ambition","emotion"],
  "NHL:WSH": ["ambition","community","emotion"],
  "PL:AR": ["process"],
  "PL:AV": ["emotion","loyalty","process"],
  "PL:BH": ["community","emotion","loyalty"],
  "PL:BO": ["ambition","emotion"],
  "PL:BR": ["community"],
  "PL:CH": ["ambition","community","emotion"],
  "PL:CP": ["ambition","community","emotion"],
  "PL:CV": ["community","emotion"],
  "PL:EV": ["emotion","loyalty","process"],
  "PL:FU": ["emotion"],
  "PL:HU": ["ambition","community"],
  "PL:IT": ["ambition","community"],
  "PL:LE": [],
  "PL:LI": ["community","emotion","loyalty"],
  "PL:LU": ["ambition","chaos","emotion"],
  "PL:MC": ["ambition","loyalty","rootedness"],
  "PL:MU": ["ambition","emotion"],
  "PL:NC": ["community","rootedness"],
  "PL:NF": ["ambition","emotion","loyalty"],
  "PL:SP": [],
  "PL:SU": ["community"],
  "PL:WH": ["community","emotion","loyalty"],
  "PL:WO": ["ambition"],
  "SA:ATA": ["ambition","emotion","loyalty"],
  "SA:BOL": ["chaos","loyalty","process"],
  "SA:CAG": ["ambition","loyalty"],
  "SA:COM": ["community"],
  "SA:FIO": ["emotion"],
  "SA:FRO": ["ambition","emotion","rootedness"],
  "SA:GEN": ["ambition"],
  "SA:INT": ["ambition"],
  "SA:JUV": ["ambition","community"],
  "SA:LAZ": ["chaos","emotion","loyalty"],
  "SA:LEC": ["chaos","loyalty","rootedness"],
  "SA:MIL": ["ambition","emotion","loyalty"],
  "SA:MON": ["loyalty"],
  "SA:NAP": ["ambition","emotion","rootedness"],
  "SA:PAR": ["ambition","community","loyalty"],
  "SA:ROM": ["ambition","emotion","loyalty"],
  "SA:SAS": ["chaos","community","process"],
  "SA:TOR": ["ambition","community","loyalty"],
  "SA:UDI": ["ambition","loyalty"],
  "SA:VEN": [],
  "TOP14:ABR": ["community","emotion","loyalty"],
  "TOP14:ASM": ["ambition","emotion","loyalty"],
  "TOP14:CAS": ["ambition","community","rootedness"],
  "TOP14:LAR": ["community","emotion","loyalty"],
  "TOP14:LOU": ["ambition","loyalty","rootedness"],
  "TOP14:MHR": ["ambition","emotion","loyalty"],
  "TOP14:PAU": ["emotion","loyalty","rootedness"],
  "TOP14:R92": ["ambition","rootedness"],
  "TOP14:RCT": ["ambition","emotion","process"],
  "TOP14:SFP": ["community"],
  "TOP14:TLS": ["ambition","loyalty","rootedness"],
  "TOP14:UBB": ["community","emotion","loyalty"],
  "TOP14:USM": ["chaos","community","emotion"],
  "TOP14:USP": ["emotion","loyalty","rootedness"]
};

// Returns up to 3 beat strings (may be empty). Never repeats the portrait's traits.
export function computeWhy(coreProfile, teamDims, sport, code){
  if(!coreProfile || !teamDims) return [];
  const you = decompressProfile(coreProfile);
  const rows = DIM.map(d => {
    const raw = coreProfile[d] ?? 0;
    return { d, raw, gap: Math.abs((+you[d]) - (+teamDims[d])), z: ((raw - MEAN[d]) / (SD[d]||1)) };
  });
  // shared = the club-aligned traits: mirror CoreCompare's smallest-gap cut (widest break in 3..5)
  const byGap = [...rows].sort((a,b)=>a.gap-b.gap);
  let cut=5, best=-1;
  for(const c of [3,4,5]){ const g = byGap[c].gap - byGap[c-1].gap; if(g>best){ best=g; cut=c; } }
  const alignSet = new Set(byGap.slice(0,cut).map(r=>r.d));
  const fg = new Set(FOREGROUND[sport + ':' + code] || []);
  return rows
    .filter(r => Math.abs(r.z) >= 0.5 && alignSet.has(r.d) && !fg.has(r.d))
    .sort((a,b)=>Math.abs(b.z)-Math.abs(a.z))
    .slice(0,3)
    .map(r => PHRASING[r.d][r.raw >= 6 ? 'high' : 'low']);
}
